### ISSUE TITLE
Tile conflicts with Disciple.Tools theme v1

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-mobile-app#539]
Before v1 there were some tiles that were static and some tiles that could be added by the user (custom tiles).
Now all tiles have the same structure following the custom tiles format.

When the v1 theme is loaded the tiles that were static are now present in the settings array.
For example, the contacts settings tiles value contains these tiles: 
```
tiles:
  coaching_checklist: {label: "Coaching Checklist"} // custom tile
  details: {label: "Details"}
  faith: {label: "Faith}
  followup: {label: "Follow Up", display_for: {…}, description: "aoeu"}
  other: {label: "Other"}
  status: {label: "Status"}
```
The mobile app already implements a few of these tiles, so there are some conflicts like:
```
 Encountered two children with the same key, `details`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

---
When we are ready to work on this issue we can update dtappdemo to with the v1 version of the theme.
